Fix person-picture-list shortcode
UCF/EVP-AFIA-Bootstrap pull request #2
Opened 2017-02-28 21:18 UTC by keeeeeegan

In #1 I fixed the name of the Person custom post type, but I had missed updating the output from a shortcode to use the fixed name.

2017-02-28 21:36 UTC, rjucf approved these changes

2017-02-28 22:00 UTC, cjg89 requested changes

2017-02-28 22:00 UTC, cjg89 commented on custom-post-types.php
> +					$email = get_post_meta($person->ID, 'person_email', True);
`person_email` probably needs to be updated to `profile_email` here as well

2017-02-28 22:03 UTC, cjg89 approved these changes

2017-03-01 13:51 UTC, jmbarne3 approved these changes

2017-03-01 13:52 UTC, merged